name: Fail Deployment Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail intentionally
        run: |
          echo "Failing deployment intentionally..."
          exit 1
