name: GitHub Deployment

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production  # 👈 Target environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Deployment
        id: create_deployment
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
              "ref": "${{ github.sha }}",
              "environment": "production",
              "description": "Triggered via GitHub Actions",
              "required_contexts": [],
              "auto_merge": false
            }')
          echo "$response"
          echo "deployment_id=$(echo $response | jq -r '.id')" >> $GITHUB_OUTPUT

      - name: Simulate Deployment
        run: echo "Deploying to production..."

      - name: Mark Deployment as Success
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ steps.create_deployment.outputs.deployment_id }}/statuses \
            -d '{
              "state": "success",
              "description": "Deployment completed successfully.",
              "environment": "production"
            }'
